<a href="https://colab.research.google.com/github/Bo-Ni/ProtBert_Notebook_set_0/blob/main/translate_NetSurfP_data_set_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## quick compare between datasets of NetSurfP2.0 and 3.0

### 2.0
https://services.healthtech.dtu.dk/service.php?NetSurfP-2.0
### 3.0
https://services.healthtech.dtu.dk/service.php?NetSurfP-3.0

In [1]:
import numpy as np
import os

In [2]:
# 0. download the files
print(os.popen('wget https://services.healthtech.dtu.dk/services/NetSurfP-2.0/training_data/Train_HHblits.npz').read())

In [3]:
data_v2 = np.load('./Train_HHblits.npz','r')

In [4]:
# what is inside the box
print(data_v2.iterkeys())
for k in data_v2.iterkeys():
    print(k)

KeysView(<numpy.lib.npyio.NpzFile object at 0x7f51a47eb690>)
pdbids
data


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: NpzFile.iterkeys is deprecated in python 3, to match the removal of dict.iterkeys. Use .keys() instead.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: NpzFile.iterkeys is deprecated in python 3, to match the removal of dict.iterkeys. Use .keys() instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [5]:
print( len(data_v2['pdbids']) )
print( data_v2['data'].shape )

10848
(10848, 1632, 68)


In [6]:
print(data_v2['pdbids'])

['12as-A' '16vp-A' '1a12-C' ... '7ahl-B' '7odc-A' '8abp-A']


In [7]:
print(data_v2['data'][0].shape)
print(data_v2['data'][1].shape)

(1632, 68)
(1632, 68)


In [8]:
reco_0_v2 = data_v2['data'][7]
reco_1_v2 = data_v2['data'][0]

In [9]:
print( reco_0_v2.shape )

(1632, 68)


In [10]:
print(data_v2['pdbids'][7])

1a62-A


In [11]:
# [0:20] Amino Acids (sparse encoding)
# [50] Seq mask (1 = seq, 0 = empty)
print(reco_0_v2[0,50])
print(reco_0_v2[0,0:20])
print(reco_0_v2[2,50])
print(reco_0_v2[2,0:20])
print(reco_0_v2[1631,50])
print(reco_0_v2[1631,0:20])

1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
print(reco_0_v2[:,50])
aa_index_list = np.where(reco_0_v2[:,50]==1)[0]
print(aa_index_list)
n_aa = aa_index_list.shape[0]
# n_aa = np.amax(aa_index_list)+1
print(n_aa)
aa_list = np.zeros(n_aa, dtype=int)
print(aa_list)
for i in range(n_aa):
  i_aa = aa_index_list[i]
  print(i_aa)
  print(np.where(reco_0_v2[i_aa,0:20]==1)[0])
  id = np.where(reco_0_v2[i_aa,0:20]==1)[0]
  if len(id)==1:
    aa_list[i_aa] = id+1
print(aa_list)

[1. 1. 1. ... 0. 0. 0.]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129]
130
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
0
[]
1
[11]
2
[9]
3
[16]
4
[3]
5
[9]
6
[8]
7
[11]
8
[16]
9
[12]
10
[17]
11
[15]
12
[3]
13
[9]
14
[7]
15
[16]
16
[9]
17
[5]
18
[3]
19
[11]
20
[]
21
[5]
22
[9]
23
[3]
24
[11]
25
[9

In [17]:
print(np.where(reco_0_v2[0,0:20]==1)[0])
print(np.where(reco_0_v2[1,0:20]==1)[0])

[]
[11]


In [19]:
# function to extract the amino acids
def read_AA_from_sparse_coding(reco_0_v2):
  # print(reco_0_v2[:,50])
  aa_index_list = np.where(reco_0_v2[:,50]==1)[0]
  # print(aa_index_list)
  # n_aa = aa_index_list.shape[0]
  n_aa = np.amax(aa_index_list)+1
  # print(n_aa)
  aa_list = np.zeros(n_aa, dtype=int)
  # print(aa_list)
  for i in range(n_aa):
    i_aa = aa_index_list[i]
    # print(i_aa)
    id = np.where(reco_0_v2[i_aa,0:20]==1)[0]
    if len(id)==1:
      aa_list[i_aa] = id+1
  # print(aa_list)  
  return aa_list, n_aa

In [20]:
aa_list,n_aa = read_AA_from_sparse_coding(reco_0_v2)
print(n_aa)
print(aa_list)

130
[ 0 12 10 17  4 10  9 12 17 13 18 16  4 10  8 17 10  6  4 12  0  6 10  4
 12 10  1 15  0 15  9 14  3  8  8  5  1  8 10  9 14  7  1  9 16  6  4  3
  8  5  6  3  6 18 10  4  8 10 14  3  6  5  6  5 10 15 16  1  3 16 16 20
 10  1  6 13  3  3  8 20 18 16 13 16 14  8 15 15  5 12 10 15 17  6  3 17
  8 16  6  9  8 15 13 13  9  4  6  4 15 20  5  1 10 10  9 18 12  4 18 12
  5  3  9 13  4 12  1 15 12  9]


In [ ]:
print( reco_0_v2[:,51] )
# not sure the meaning
print( len(np.where(reco_0_v2[:,52]==1)[0]) )

[0. 0. 0. ... 0. 0. 0.]
330


In [ ]:
print(reco_0_v2[0,57:65])
print(len(reco_0_v2[0,57:65]))
print(reco_0_v2[10,65:67])
print(reco_0_v2[10,65])
print(reco_0_v2[10,66])
# print(reco_0_v2[:,54])

[0. 0. 0. 0. 0. 0. 0. 1.]
8
[-52.9 -57.3]
-52.9
-57.3


19
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# need the code of AA
print(len(np.unique(aa_list)))
print(np.unique(aa_list))

19
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
['M' 'K' 'T' 'A' 'Y' 'I' 'A' 'K' 'Q' 'R' 'Q' 'I' 'S' 'F' 'V' 'K' 'S' 'H'
 'F' 'S' 'R' 'Q' 'L' 'E' 'E' 'R' 'L' 'G' 'L' 'I' 'E' 'V' 'Q' 'A' 'P' 'I'
 'L' 'S' 'R' 'V' 'G' 'D' 'G' 'T' 'Q' 'D' 'N' 'L' 'S' 'G' 'A' 'E' 'K' 'A'
 'V' 'Q' 'V' 'K' 'V' 'K' 'A' 'L' 'P' 'D' 'A' 'Q' 'F' 'E' 'V' 'V' 'H' 'S'
 'L' 'A' 'K' 'W' 'K' 'R' 'Q' 'T' 'L' 'G' 'Q' 'H' 'D' 'F' 'S' 'A' 'G' 'E'
 'G' 'L' 'Y' 'T' 'H' 'M' 'K' 'A' 'L' 'R' 'P' 'D' 'E' 'D' 'R' 'L' 'S' 'P'
 'L' 'H' 'S' 'V' 'Y' 'V' 'D' 'Q' 'W' 'D' 'W' 'E' 'R' 'V' 'M' 'G' 'D' 'G'
 'E' 'R' 'Q' 'F' 'S' 'T' 'L' 'K' 'S' 'T' 'V' 'E' 'A' 'I' 'W' 'A' 'G' 'I'
 'K' 'A' 'T' 'E' 'A' 'A' 'V' 'S' 'E' 'E' 'F' 'G' 'L' 'A' 'P' 'F' 'L' 'P'
 'D' 'Q' 'I' 'H' 'F' 'V' 'H' 'S' 'Q' 'E' 'L' 'L' 'S' 'R' 'Y' 'P' 'D' 'L'
 'D' 'A' 'K' 'G' 'R' 'E' 'R' 'A' 'I' 'A' 'K' 'D' 'L' 'G' 'A' 'V' 'F' 'L'
 'V' 'G' 'I' 'G' 'G' 'K' 'L' 'S' 'D' 'G' 'H' 'R' 'H' 'D' 'V' 'R' 'A' 'P'
 'D' 'Y' 'D' 'D' 'W' 'S' 'T' 'P' 'S' 'E' 'L' 'G' 'H' 'A' 'G' '

In [ ]:
aa_name_reco_0_v2=np.array(list('MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEKAVQVKVKALPDAQFEVVHSLAKWKRQTLGQHDFSAGEGLYTHMKALRPDEDRLSPLHSVYVDQWDWERVMGDGERQFSTLKSTVEAIWAGIKATEAAVSEEFGLAPFLPDQIHFVHSQELLSRYPDLDAKGRERAIAKDLGAVFLVGIGGKLSDGHRHDVRAPDYDDWSTPSELGHAGLNGDILVWNPVLEDAFELSSMGIRVDADTLKHQLALTGDEDRLELEWHQALLRGEMPQTIGGGIGQSRLTMLLLQLPHIGQVQAGVWPAAVRESVPSLL'))
# print(aa_name_reco_0_v2)
print(np.unique(aa_name_reco_0_v2))

['A' 'D' 'E' 'F' 'G' 'H' 'I' 'K' 'L' 'M' 'N' 'P' 'Q' 'R' 'S' 'T' 'V' 'W'
 'Y']


In [ ]:
aa_list,n_aa = read_AA_from_sparse_coding(reco_1_v2)
print(len(np.unique(aa_list)))
print(np.unique(aa_list))

20
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
aa_name_reco_1_v2=np.array(list('SRMPSPPMPVPPAALFNRLLDDLGFSAGPALCTMLDTWNEDLFSALPTNADLYRECKFLSTLPSDVVEWGDAYVPERTQIDIRAHGDVAFPTLPATRDGLGLYYEALSRFFHAELRAREESYRTVLANFCSALYRYLRASVRQLHRQAHMRGRDRDLGEMLRATIADRYYRETARLARVLFLHLYLFLTREILWAAYAEQMMRPDLFDCLCCDLESWRQLAGLFQPFMFVNGALTVRGVPIEARRLRELNHIREHLNLPLVRSAATEEPGAPLTTPPTLHGNQARASGYFMVLIRAKLDSYSSFTTSPSEAVMREHAYSRAPTKNNYGSTIEGLLDLPDDDAPEEAGLAAPRLSFLPAGHTRRLST'))
# print(aa_name_reco_0_v2)
print("".join(np.unique(aa_name_reco_1_v2)))

ACDEFGHIKLMNPQRSTVWY


In [21]:
# function to extract the amino acids
def read_info_from_sparse_coding(reco_0_v2):
  # print(reco_0_v2[:,50])
  aa_index_list = np.where(reco_0_v2[:,50]==1)[0]
  # print(aa_index_list)
  # n_aa = aa_index_list.shape[0]
  n_aa = np.amax(aa_index_list)+1
  # print(n_aa)
  aa_list = np.zeros(n_aa, dtype=int)
  ss_list = np.zeros(n_aa, dtype=int)
  phi_list = np.zeros(n_aa)
  psi_list = np.zeros(n_aa)
  # print(aa_list)
  for i in range(n_aa):
    i_aa = aa_index_list[i]
    # print(i_aa)
    id = np.where(reco_0_v2[i_aa,0:20]==1)[0]
    if len(id)==1:
      aa_list[i_aa] = id+1
    id = np.where(reco_0_v2[i_aa,57:65]==1)[0]
    if len(id)==1:
      ss_list[i_aa] = id+1
      
    phi_list[i_aa] = reco_0_v2[i_aa,65]
    psi_list[i_aa] = reco_0_v2[i_aa,66]
  # print(aa_list)  
  return n_aa,aa_list,ss_list,phi_list,psi_list

In [22]:
n_aa,aa_list,ss_list,phi_list,psi_list = read_info_from_sparse_coding(reco_0_v2)

In [23]:
print(n_aa)
print(aa_list)
print(ss_list)
print(phi_list)
print(psi_list)

130
[ 0 12 10 17  4 10  9 12 17 13 18 16  4 10  8 17 10  6  4 12  0  6 10  4
 12 10  1 15  0 15  9 14  3  8  8  5  1  8 10  9 14  7  1  9 16  6  4  3
  8  5  6  3  6 18 10  4  8 10 14  3  6  5  6  5 10 15 16  1  3 16 16 20
 10  1  6 13  3  3  8 20 18 16 13 16 14  8 15 15  5 12 10 15 17  6  3 17
  8 16  6  9  8 15 13 13  9  4  6  4 15 20  5  1 10 10  9 18 12  4 18 12
  5  3  9 13  4 12  1 15 12  9]
[8 4 2 2 2 2 2 7 6 8 2 2 2 2 2 2 2 2 2 7 7 7 8 8 8 8 7 7 6 8 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 7 7 8 8 5 5 5 5 5 5 5 5 5 8 7 7 6 8 5 5 5 5 8 1 1 1 7 7 8 8
 8 7 7 8 5 5 5 8 2 2 2 2 2 2 7 7 8 8 7 7 8 5 5 5 5 5 5 5 8 8 8 7 7 8 8 6 5
 5 5 5 5 5 5 5 5 7 7 4 8 8 8 8 8 8 8 8]
[ 360.  -134.2  -56.5  -65.1  -62.3  -62.3  -60.4  -93.9  -99.6  -57.6
  -57.1  -61.6  -73.6  -67.8  -60.8  -60.   -55.8  -68.8  -60.3  -63.9
 -113.5   84.7 -104.1 -135.7   48.1  -75.8  -48.1  -79.   -93.1  -70.6
  -51.4  -60.6  -76.1  -66.5  -60.1  -58.9  -58.7  -64.3  -62.1  -63.6
  -63.4  -62.   -61.6  -62.4  -82.7   86.6  -93.3 

In [ ]:
AA_Dict = np.array(list('ARNDBCEQZGHILKMFPSTWYV'))
AA_Dict = np.array(list('ABDEFGHIKLMNPQRSTVWY'))
AA_Dict = np.array(list('ACDEFGHIKLMNPQRSTVWY'))

print(AA_Dict)
print(AA_Dict.shape)
print(AA_Dict[[1,2]])

['A' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'K' 'L' 'M' 'N' 'P' 'Q' 'R' 'S' 'T' 'V'
 'W' 'Y']
(20,)
['C' 'D']


In [ ]:
# only need to consider 20 AA according to the web
# how to handle other AA?

In [24]:
# translate num to code
# n_aa,aa_list,ss_list,phi_list,psi_list
def translate_AA_to_print(aa_list):
  # AA_Dict = np.array(list('ACDEFGHIKLMNPQRSTVWY'))
  # aa_name_list=AA_Dict[aa_list-1]

  # to be save with 0 position problem: mark it as X
  AA_Dict = np.array(list('XACDEFGHIKLMNPQRSTVWY'))
  aa_name_list=AA_Dict[aa_list]
  return aa_name_list

In [25]:
print(aa_list)
print(translate_AA_to_print(aa_list))
print("".join(translate_AA_to_print(aa_list)))

[ 0 12 10 17  4 10  9 12 17 13 18 16  4 10  8 17 10  6  4 12  0  6 10  4
 12 10  1 15  0 15  9 14  3  8  8  5  1  8 10  9 14  7  1  9 16  6  4  3
  8  5  6  3  6 18 10  4  8 10 14  3  6  5  6  5 10 15 16  1  3 16 16 20
 10  1  6 13  3  3  8 20 18 16 13 16 14  8 15 15  5 12 10 15 17  6  3 17
  8 16  6  9  8 15 13 13  9  4  6  4 15 20  5  1 10 10  9 18 12  4 18 12
  5  3  9 13  4 12  1 15 12  9]
['X' 'N' 'L' 'T' 'E' 'L' 'K' 'N' 'T' 'P' 'V' 'S' 'E' 'L' 'I' 'T' 'L' 'G'
 'E' 'N' 'X' 'G' 'L' 'E' 'N' 'L' 'A' 'R' 'X' 'R' 'K' 'Q' 'D' 'I' 'I' 'F'
 'A' 'I' 'L' 'K' 'Q' 'H' 'A' 'K' 'S' 'G' 'E' 'D' 'I' 'F' 'G' 'D' 'G' 'V'
 'L' 'E' 'I' 'L' 'Q' 'D' 'G' 'F' 'G' 'F' 'L' 'R' 'S' 'A' 'D' 'S' 'S' 'Y'
 'L' 'A' 'G' 'P' 'D' 'D' 'I' 'Y' 'V' 'S' 'P' 'S' 'Q' 'I' 'R' 'R' 'F' 'N'
 'L' 'R' 'T' 'G' 'D' 'T' 'I' 'S' 'G' 'K' 'I' 'R' 'P' 'P' 'K' 'E' 'G' 'E'
 'R' 'Y' 'F' 'A' 'L' 'L' 'K' 'V' 'N' 'E' 'V' 'N' 'F' 'D' 'K' 'P' 'E' 'N'
 'A' 'R' 'N' 'K']
XNLTELKNTPVSELITLGENXGLENLARXRKQDIIFAILKQHAKSGEDIFGDGVLEILQDGFGFLRSADSSYLA

In [ ]:
n_aa_0,aa_list_0,ss_list_0,phi_list_0,psi_list_0 = read_info_from_sparse_coding(reco_0_v2)
n_aa_1,aa_list_1,ss_list_1,phi_list_1,psi_list_1 = read_info_from_sparse_coding(reco_1_v2)

In [ ]:
print(np.unique(ss_list_0))

[1 2 4 5 6 7 8]


In [ ]:
def translate_SS_to_print(ss_list):
  # AA_Dict = np.array(list('ACDEFGHIKLMNPQRSTVWY'))
  # aa_name_list=AA_Dict[aa_list-1]

  # to be save with 0 position problem: mark it as X
  SS_Dict = np.array(list('XGHIBESTC'))
  ss_name_list=SS_Dict[ss_list]
  return ss_name_list

In [ ]:
print(ss_list_0)
print("".join(translate_SS_to_print(ss_list_0)))
print(ss_list_1.shape)
print("".join(translate_SS_to_print(ss_list_1)))

[8 8 8 8 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 8 5 5 5 8 8 8 8 6 5
 5 5 7 7 6 6 8 6 8 8 7 7 7 7 8 8 8 8 5 5 8 8 6 6 6 7 7 8 8 5 5 5 8 6 8 8 7
 7 2 2 2 2 2 2 2 2 7 7 8 8 7 7 8 5 5 5 5 5 5 5 5 5 8 7 7 8 6 8 8 8 6 6 8 8
 6 5 5 5 5 5 5 5 5 5 5 8 8 7 7 8 8 6 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 6 8 8 8 8 8 6 8 6 6 8 5 5 5 5 2 2 2 2 2 2 2 6 6 6 6 8 2 2 2 2
 2 2 2 2 2 2 2 2 6 5 5 5 5 5 8 8 6 6 8 8 6 6 6 8 8 6 6 8 8 8 7 7 7 4 8 8 6
 6 4 8 7 7 6 6 4 8 6 5 5 5 5 5 5 5 5 7 7 7 7 5 5 5 5 5 5 5 5 5 5 4 8 8 2 2
 2 2 2 2 2 2 2 2 2 7 8 7 7 1 1 1 6 2 2 2 2 2 2 2 7 7 8 6 8 8 5 5 5 5 5 5 5
 2 2 2 2 2 2 2 2 2 7 8 6 8 1 1 1 7 6 8 8 8 8 8 2 2 2 2 2 2 8 8 6 8 8]
CCCCHHHHHHHHHHHHHHHHHHHHHHHCEEECCCCSEEETTSSCSCCTTTTCCCCEECCSSSTTCCEEECSCCTTHHHHHHHHTTCCTTCEEEEEEEEECTTCSCCCSSCCSEEEEEEEEEECCTTCCSHHHHHHHHHHHHHHHHHHHHHHHHHSCCCCCSCSSCEEEEHHHHHHHSSSSCHHHHHHHHHHHHSEEEEECCSSCCSSSCCSSCCCTTTBCCSSBCTTSSBCSEEEEEEEETTTTEEEEEEEEEEBCCHHHHHHHHHHHTCTTGGGSHHHHHHHTTCSCCEEEEEEEHHHHHHHHHTCSCGGGTSCCCCCHHHHHHCCSCC

In [ ]:
print( phi_list_0 )
print( aa_list_0 )
" ".join(str(x) for x in phi_list_0)
# np.fromstring(phi_list_0, dtype=int)
#print("".join(phi_list_0.tostring()))

[   0.     0.     0.   360.   -41.6  -55.5  -54.4  -54.3  -61.4  -86.1
  -52.9  -53.8  -55.7  -64.6  -61.1  -62.5  -80.5  -53.4  -67.3  -57.8
  -70.4  -59.1  -75.1  -74.7  -87.6  -75.4 -123.5   61.8 -104.2 -102.2
  -76.6 -124.3  -73.8  -87.   -63.3 -128.7 -106.8 -148.5  -81.   -70.7
  107.3 -106.1   71.2  -95.3 -101.8  -72.7  -89.3   64.6  -65.7   82.1
 -102.3  -97.2  -70.1  -95.3  -71.1  -77.3 -113.   -99.   -88.   -77.6
  -73.5 -123.1  -72.8 -107.8 -120.2 -113.4 -135.  -136.4  -83.1  -79.2
  -83.3  176.6  -90.2  -36.5  -92.4  -51.8  -73.1  -73.1  -63.2  -66.
  -71.9  -64.2  -67.5  -95.    61.6  -68.2  -94.8  -84.5   96.1 -117.9
 -147.2 -123.9 -143.  -126.8  -90.1  -75.3 -112.8 -150.4 -111.4 -126.6
  -75.4 -110.4  -52.9  -89.7 -129.4  -71.2 -157.5  -52.9 -114.6 -101.5
 -114.   -76.5  -93.3 -106.7 -115.9 -150.6  -72.5  -95.7 -129.1 -149.5
 -140.9  -78.3  -96.3 -109.3  -60.5   76.5  -99.7  -80.5 -157.7  -62.5
  -56.1  -72.   -66.8  -55.2  -71.9  -56.7  -57.5  -77.1  -62.1  -57.8
  -67.7

'0.0 0.0 0.0 360.0 -41.6 -55.5 -54.4 -54.3 -61.4 -86.1 -52.9 -53.8 -55.7 -64.6 -61.1 -62.5 -80.5 -53.4 -67.3 -57.8 -70.4 -59.1 -75.1 -74.7 -87.6 -75.4 -123.5 61.8 -104.2 -102.2 -76.6 -124.3 -73.8 -87.0 -63.3 -128.7 -106.8 -148.5 -81.0 -70.7 107.3 -106.1 71.2 -95.3 -101.8 -72.7 -89.3 64.6 -65.7 82.1 -102.3 -97.2 -70.1 -95.3 -71.1 -77.3 -113.0 -99.0 -88.0 -77.6 -73.5 -123.1 -72.8 -107.8 -120.2 -113.4 -135.0 -136.4 -83.1 -79.2 -83.3 176.6 -90.2 -36.5 -92.4 -51.8 -73.1 -73.1 -63.2 -66.0 -71.9 -64.2 -67.5 -95.0 61.6 -68.2 -94.8 -84.5 96.1 -117.9 -147.2 -123.9 -143.0 -126.8 -90.1 -75.3 -112.8 -150.4 -111.4 -126.6 -75.4 -110.4 -52.9 -89.7 -129.4 -71.2 -157.5 -52.9 -114.6 -101.5 -114.0 -76.5 -93.3 -106.7 -115.9 -150.6 -72.5 -95.7 -129.1 -149.5 -140.9 -78.3 -96.3 -109.3 -60.5 76.5 -99.7 -80.5 -157.7 -62.5 -56.1 -72.0 -66.8 -55.2 -71.9 -56.7 -57.5 -77.1 -62.1 -57.8 -67.7 -70.4 -74.0 -66.6 -66.6 -52.3 -66.1 -71.7 -79.4 -67.8 -59.9 -67.1 -140.8 -75.4 -115.1 62.2 -80.0 -69.1 -85.0 -148.4 -69.5 -57.

In [ ]:
print( reco_0_v2[0,0:68] )

[  0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   1.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   1.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   1.           0.           0.           0.           0.
   0.           0.           0.39338122   1.           1.
   1.           0.           1.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           1.
   0.           0.         200.1       ]
