<a href="https://colab.research.google.com/github/Bo-Ni/ProtBert_Notebook_set_0/blob/main/translate_NetSurfP_data_set_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## quick compare between datasets of NetSurfP2.0 and 3.0

### 2.0
https://services.healthtech.dtu.dk/service.php?NetSurfP-2.0
### 3.0
https://services.healthtech.dtu.dk/service.php?NetSurfP-3.0

In [1]:
import numpy as np
import os

In [2]:
# 0. download the files
print(os.popen('wget https://services.healthtech.dtu.dk/services/NetSurfP-2.0/training_data/Train_HHblits.npz').read())

In [3]:
data_v2 = np.load('./Train_HHblits.npz')

In [4]:
# what is inside the box
print(data_v2.iterkeys())
for k in data_v2.iterkeys():
    print(k)

KeysView(<numpy.lib.npyio.NpzFile object at 0x7fc81112a710>)
pdbids
data


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: NpzFile.iterkeys is deprecated in python 3, to match the removal of dict.iterkeys. Use .keys() instead.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: NpzFile.iterkeys is deprecated in python 3, to match the removal of dict.iterkeys. Use .keys() instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [5]:
print( len(data_v2['pdbids']) )
print( data_v2['data'].shape )

10848
(10848, 1632, 68)


In [6]:
print(data_v2['pdbids'])

['12as-A' '16vp-A' '1a12-C' ... '7ahl-B' '7odc-A' '8abp-A']


In [15]:
print(data_v2['data'][0].shape)
print(data_v2['data'][1].shape)

(1632, 68)
(1632, 68)


In [16]:
reco_0_v2 = data_v2['data'][0]
reco_1_v2 = data_v2['data'][1]

In [18]:
print( reco_0_v2.shape )

(1632, 68)


In [23]:
print(data_v2['pdbids'][0])

12as-A


In [26]:
# [0:20] Amino Acids (sparse encoding)
# [50] Seq mask (1 = seq, 0 = empty)
print(reco_0_v2[0,50])
print(reco_0_v2[0,0:20])
print(reco_0_v2[2,50])
print(reco_0_v2[2,0:20])
print(reco_0_v2[1631,50])
print(reco_0_v2[1631,0:20])

1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [87]:
print(reco_0_v2[:,50])
aa_index_list = np.where(reco_0_v2[:,50]==1)[0]
print(aa_index_list)
n_aa = aa_index_list.shape[0]
# n_aa = np.amax(aa_index_list)+1
print(n_aa)
aa_list = np.zeros(n_aa, dtype=int)
print(aa_list)
for i in range(n_aa):
  i_aa = aa_index_list[i]
  # print(i_aa)
  aa_list[i_aa] = np.where(reco_0_v2[i_aa,0:20]==1)[0]+1
print(aa_list)

[1. 1. 1. ... 0. 0. 0.]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 24

In [88]:
# function to extract the amino acids
def read_AA_from_sparse_coding(reco_0_v2):
  # print(reco_0_v2[:,50])
  aa_index_list = np.where(reco_0_v2[:,50]==1)[0]
  # print(aa_index_list)
  # n_aa = aa_index_list.shape[0]
  n_aa = np.amax(aa_index_list)+1
  # print(n_aa)
  aa_list = np.zeros(n_aa, dtype=int)
  # print(aa_list)
  for i in range(n_aa):
    i_aa = aa_index_list[i]
    # print(i_aa)
    aa_list[i_aa] = np.where(reco_0_v2[i_aa,0:20]==1)[0]+1
  # print(aa_list)  
  return aa_list, n_aa

In [93]:
aa_list,n_aa = read_AA_from_sparse_coding(reco_0_v2)
print(n_aa)
print(aa_list)

330
[11  9 17  1 20  8  1  9 14 15 14  8 16  5 18  9 16  7  5 16 15 14 10  4
  4 15 10  6 10  8  4 18 14  1 13  8 10 16 15 18  6  3  6 17 14  3 12 10
 16  6  1  4  9  1 18 14 18  9 18  9  1 10 13  3  1 14  5  4 18 18  7 16
 10  1  9 19  9 15 14 17 10  6 14  7  3  5 16  1  6  4  6 10 20 17  7 11
  9  1 10 15 13  3  4  3 15 10 16 13 10  7 16 18 20 18  3 14 19  3 19  4
 15 18 11  6  3  6  4 15 14  5 16 17 10  9 16 17 18  4  1  8 19  1  6  8
  9  1 17  4  1  1 18 16  4  4  5  6 10  1 13  5 10 13  3 14  8  7  5 18
  7 16 14  4 10 10 16 15 20 13  3 10  3  1  9  6 15  4 15  1  8  1  9  3
 10  6  1 18  5 10 18  6  8  6  6  9 10 16  3  6  7 15  7  3 18 15  1 13
  3 20  3  3 19 16 17 13 16  4 10  6  7  1  6 10 12  6  3  8 10 18 19 12
 13 18 10  4  3  1  5  4 10 16 16 11  6  8 15 18  3  1  3 17 10  9  7 14
 10  1 10 17  6  3  4  3 15 10  4 10  4 19  7 14  1 10 10 15  6  4 11 13
 14 17  8  6  6  6  8  6 14 16 15 10 17 11 10 10 10 14 10 13  7  8  6 14
 18 14  1  6 18 19 13  1  1 18 15  4 16 18 13 1

In [52]:
print( reco_0_v2[:,51] )
# not sure the meaning
print( len(np.where(reco_0_v2[:,52]==1)[0]) )

[0. 0. 0. ... 0. 0. 0.]
330


In [62]:
print(reco_0_v2[0,57:65])
print(len(reco_0_v2[0,57:65]))
print(reco_0_v2[10,65:67])
print(reco_0_v2[10,65])
print(reco_0_v2[10,66])
# print(reco_0_v2[:,54])

[0. 0. 0. 0. 0. 0. 0. 1.]
8
[-52.9 -57.3]
-52.9
-57.3


19
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [104]:
# need the code of AA
print(len(np.unique(aa_list)))
print(np.unique(aa_list))

19
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
['M' 'K' 'T' 'A' 'Y' 'I' 'A' 'K' 'Q' 'R' 'Q' 'I' 'S' 'F' 'V' 'K' 'S' 'H'
 'F' 'S' 'R' 'Q' 'L' 'E' 'E' 'R' 'L' 'G' 'L' 'I' 'E' 'V' 'Q' 'A' 'P' 'I'
 'L' 'S' 'R' 'V' 'G' 'D' 'G' 'T' 'Q' 'D' 'N' 'L' 'S' 'G' 'A' 'E' 'K' 'A'
 'V' 'Q' 'V' 'K' 'V' 'K' 'A' 'L' 'P' 'D' 'A' 'Q' 'F' 'E' 'V' 'V' 'H' 'S'
 'L' 'A' 'K' 'W' 'K' 'R' 'Q' 'T' 'L' 'G' 'Q' 'H' 'D' 'F' 'S' 'A' 'G' 'E'
 'G' 'L' 'Y' 'T' 'H' 'M' 'K' 'A' 'L' 'R' 'P' 'D' 'E' 'D' 'R' 'L' 'S' 'P'
 'L' 'H' 'S' 'V' 'Y' 'V' 'D' 'Q' 'W' 'D' 'W' 'E' 'R' 'V' 'M' 'G' 'D' 'G'
 'E' 'R' 'Q' 'F' 'S' 'T' 'L' 'K' 'S' 'T' 'V' 'E' 'A' 'I' 'W' 'A' 'G' 'I'
 'K' 'A' 'T' 'E' 'A' 'A' 'V' 'S' 'E' 'E' 'F' 'G' 'L' 'A' 'P' 'F' 'L' 'P'
 'D' 'Q' 'I' 'H' 'F' 'V' 'H' 'S' 'Q' 'E' 'L' 'L' 'S' 'R' 'Y' 'P' 'D' 'L'
 'D' 'A' 'K' 'G' 'R' 'E' 'R' 'A' 'I' 'A' 'K' 'D' 'L' 'G' 'A' 'V' 'F' 'L'
 'V' 'G' 'I' 'G' 'G' 'K' 'L' 'S' 'D' 'G' 'H' 'R' 'H' 'D' 'V' 'R' 'A' 'P'
 'D' 'Y' 'D' 'D' 'W' 'S' 'T' 'P' 'S' 'E' 'L' 'G' 'H' 'A' 'G' '

In [106]:
aa_name_reco_0_v2=np.array(list('MKTAYIAKQRQISFVKSHFSRQLEERLGLIEVQAPILSRVGDGTQDNLSGAEKAVQVKVKALPDAQFEVVHSLAKWKRQTLGQHDFSAGEGLYTHMKALRPDEDRLSPLHSVYVDQWDWERVMGDGERQFSTLKSTVEAIWAGIKATEAAVSEEFGLAPFLPDQIHFVHSQELLSRYPDLDAKGRERAIAKDLGAVFLVGIGGKLSDGHRHDVRAPDYDDWSTPSELGHAGLNGDILVWNPVLEDAFELSSMGIRVDADTLKHQLALTGDEDRLELEWHQALLRGEMPQTIGGGIGQSRLTMLLLQLPHIGQVQAGVWPAAVRESVPSLL'))
# print(aa_name_reco_0_v2)
print(np.unique(aa_name_reco_0_v2))

['A' 'D' 'E' 'F' 'G' 'H' 'I' 'K' 'L' 'M' 'N' 'P' 'Q' 'R' 'S' 'T' 'V' 'W'
 'Y']


In [107]:
aa_list,n_aa = read_AA_from_sparse_coding(reco_1_v2)
print(len(np.unique(aa_list)))
print(np.unique(aa_list))

20
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [109]:
aa_name_reco_1_v2=np.array(list('SRMPSPPMPVPPAALFNRLLDDLGFSAGPALCTMLDTWNEDLFSALPTNADLYRECKFLSTLPSDVVEWGDAYVPERTQIDIRAHGDVAFPTLPATRDGLGLYYEALSRFFHAELRAREESYRTVLANFCSALYRYLRASVRQLHRQAHMRGRDRDLGEMLRATIADRYYRETARLARVLFLHLYLFLTREILWAAYAEQMMRPDLFDCLCCDLESWRQLAGLFQPFMFVNGALTVRGVPIEARRLRELNHIREHLNLPLVRSAATEEPGAPLTTPPTLHGNQARASGYFMVLIRAKLDSYSSFTTSPSEAVMREHAYSRAPTKNNYGSTIEGLLDLPDDDAPEEAGLAAPRLSFLPAGHTRRLST'))
# print(aa_name_reco_0_v2)
print("".join(np.unique(aa_name_reco_1_v2)))

ACDEFGHIKLMNPQRSTVWY


In [131]:
# function to extract the amino acids
def read_info_from_sparse_coding(reco_0_v2):
  # print(reco_0_v2[:,50])
  aa_index_list = np.where(reco_0_v2[:,50]==1)[0]
  # print(aa_index_list)
  # n_aa = aa_index_list.shape[0]
  n_aa = np.amax(aa_index_list)+1
  # print(n_aa)
  aa_list = np.zeros(n_aa, dtype=int)
  ss_list = np.zeros(n_aa, dtype=int)
  phi_list = np.zeros(n_aa)
  psi_list = np.zeros(n_aa)
  # print(aa_list)
  for i in range(n_aa):
    i_aa = aa_index_list[i]
    # print(i_aa)
    aa_list[i_aa] = np.where(reco_0_v2[i_aa,0:20]==1)[0]+1
    ss_list[i_aa] = np.where(reco_0_v2[i_aa,57:65]==1)[0]+1
    phi_list[i_aa] = reco_0_v2[i_aa,65]
    psi_list[i_aa] = reco_0_v2[i_aa,66]
  # print(aa_list)  
  return n_aa,aa_list,ss_list,phi_list,psi_list

In [91]:
n_aa,aa_list,ss_list,phi_list,psi_list = read_info_from_sparse_coding(reco_0_v2)

In [92]:
print(n_aa)
print(aa_list)
print(ss_list)
print(phi_list)
print(psi_list)

330
[11  9 17  1 20  8  1  9 14 15 14  8 16  5 18  9 16  7  5 16 15 14 10  4
  4 15 10  6 10  8  4 18 14  1 13  8 10 16 15 18  6  3  6 17 14  3 12 10
 16  6  1  4  9  1 18 14 18  9 18  9  1 10 13  3  1 14  5  4 18 18  7 16
 10  1  9 19  9 15 14 17 10  6 14  7  3  5 16  1  6  4  6 10 20 17  7 11
  9  1 10 15 13  3  4  3 15 10 16 13 10  7 16 18 20 18  3 14 19  3 19  4
 15 18 11  6  3  6  4 15 14  5 16 17 10  9 16 17 18  4  1  8 19  1  6  8
  9  1 17  4  1  1 18 16  4  4  5  6 10  1 13  5 10 13  3 14  8  7  5 18
  7 16 14  4 10 10 16 15 20 13  3 10  3  1  9  6 15  4 15  1  8  1  9  3
 10  6  1 18  5 10 18  6  8  6  6  9 10 16  3  6  7 15  7  3 18 15  1 13
  3 20  3  3 19 16 17 13 16  4 10  6  7  1  6 10 12  6  3  8 10 18 19 12
 13 18 10  4  3  1  5  4 10 16 16 11  6  8 15 18  3  1  3 17 10  9  7 14
 10  1 10 17  6  3  4  3 15 10  4 10  4 19  7 14  1 10 10 15  6  4 11 13
 14 17  8  6  6  6  8  6 14 16 15 10 17 11 10 10 10 14 10 13  7  8  6 14
 18 14  1  6 18 19 13  1  1 18 15  4 16 18 13 1

In [110]:
AA_Dict = np.array(list('ARNDBCEQZGHILKMFPSTWYV'))
AA_Dict = np.array(list('ABDEFGHIKLMNPQRSTVWY'))
AA_Dict = np.array(list('ACDEFGHIKLMNPQRSTVWY'))

print(AA_Dict)
print(AA_Dict.shape)
print(AA_Dict[[1,2]])

['A' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'K' 'L' 'M' 'N' 'P' 'Q' 'R' 'S' 'T' 'V'
 'W' 'Y']
(20,)
['C' 'D']


In [ ]:
# only need to consider 20 AA according to the web
# how to handle other AA?

In [115]:
# translate num to code
# n_aa,aa_list,ss_list,phi_list,psi_list
def translate_AA_to_print(aa_list):
  # AA_Dict = np.array(list('ACDEFGHIKLMNPQRSTVWY'))
  # aa_name_list=AA_Dict[aa_list-1]

  # to be save with 0 position problem: mark it as X
  AA_Dict = np.array(list('XACDEFGHIKLMNPQRSTVWY'))
  aa_name_list=AA_Dict[aa_list]
  return aa_name_list

In [116]:
print(aa_list)
print(translate_AA_to_print(aa_list))
print("".join(translate_AA_to_print(aa_list)))

[16 15 11 13 16 13 13 11 13 18 13 13  1  1 10  5 12 15 10 10  3  3 10  6
  5 16  1  6 13  1 10  2 17 11 10  3 17 19 12  4  3 10  5 16  1 10 13 17
 12  1  3 10 20 15  4  2  9  5 10 16 17 10 13 16  3 18 18  4 19  6  3  1
 20 18 13  4 15 17 14  8  3  8 15  1  7  6  3 18  1  5 13 17 10 13  1 17
 15  3  6 10  6 10 20 20  4  1 10 16 15  5  5  7  1  4 10 15  1 15  4  4
 16 20 15 17 18 10  1 12  5  2 16  1 10 20 15 20 10 15  1 16 18 15 14 10
  7 15 14  1  7 11 15  6 15  3 15  3 10  6  4 11 10 15  1 17  8  1  3 15
 20 20 15  4 17  1 15 10  1 15 18 10  5 10  7 10 20 10  5 10 17 15  4  8
 10 19  1  1 20  1  4 14 11 11 15 13  3 10  5  3  2 10  2  2  3 10  4 16
 19 15 14 10  1  6 10  5 14 13  5 11  5 18 12  6  1 10 17 18 15  6 18 13
  8  4  1 15 15 10 15  4 10 12  7  8 15  4  7 10 12 10 13 10 18 15 16  1
  1 17  4  4 13  6  1 13 10 17 17 13 13 17 10  7  6 12 14  1 15  1 16  6
 20  5 11 18 10  8 15  1  9 10  3 16 20 16 16  5 17 17 16 13 16  4  1 18
 11 15  4  7  1 20 16 15  1 13 17  9 12 12 20  6 16

In [118]:
n_aa_0,aa_list_0,ss_list_0,phi_list_0,psi_list_0 = read_info_from_sparse_coding(reco_0_v2)
n_aa_1,aa_list_1,ss_list_1,phi_list_1,psi_list_1 = read_info_from_sparse_coding(reco_1_v2)

In [120]:
print(np.unique(ss_list_0))

[1 2 4 5 6 7 8]


In [132]:
def translate_SS_to_print(ss_list):
  # AA_Dict = np.array(list('ACDEFGHIKLMNPQRSTVWY'))
  # aa_name_list=AA_Dict[aa_list-1]

  # to be save with 0 position problem: mark it as X
  SS_Dict = np.array(list('XGHIBESTC'))
  ss_name_list=SS_Dict[ss_list]
  return ss_name_list

In [135]:
print(ss_list_0)
print("".join(translate_SS_to_print(ss_list_0)))
print(ss_list_1.shape)
print("".join(translate_SS_to_print(ss_list_1)))

[8 8 8 8 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 8 5 5 5 8 8 8 8 6 5
 5 5 7 7 6 6 8 6 8 8 7 7 7 7 8 8 8 8 5 5 8 8 6 6 6 7 7 8 8 5 5 5 8 6 8 8 7
 7 2 2 2 2 2 2 2 2 7 7 8 8 7 7 8 5 5 5 5 5 5 5 5 5 8 7 7 8 6 8 8 8 6 6 8 8
 6 5 5 5 5 5 5 5 5 5 5 8 8 7 7 8 8 6 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 6 8 8 8 8 8 6 8 6 6 8 5 5 5 5 2 2 2 2 2 2 2 6 6 6 6 8 2 2 2 2
 2 2 2 2 2 2 2 2 6 5 5 5 5 5 8 8 6 6 8 8 6 6 6 8 8 6 6 8 8 8 7 7 7 4 8 8 6
 6 4 8 7 7 6 6 4 8 6 5 5 5 5 5 5 5 5 7 7 7 7 5 5 5 5 5 5 5 5 5 5 4 8 8 2 2
 2 2 2 2 2 2 2 2 2 7 8 7 7 1 1 1 6 2 2 2 2 2 2 2 7 7 8 6 8 8 5 5 5 5 5 5 5
 2 2 2 2 2 2 2 2 2 7 8 6 8 1 1 1 7 6 8 8 8 8 8 2 2 2 2 2 2 8 8 6 8 8]
CCCCHHHHHHHHHHHHHHHHHHHHHHHCEEECCCCSEEETTSSCSCCTTTTCCCCEECCSSSTTCCEEECSCCTTHHHHHHHHTTCCTTCEEEEEEEEECTTCSCCCSSCCSEEEEEEEEEECCTTCCSHHHHHHHHHHHHHHHHHHHHHHHHHSCCCCCSCSSCEEEEHHHHHHHSSSSCHHHHHHHHHHHHSEEEEECCSSCCSSSCCSSCCCTTTBCCSSBCTTSSBCSEEEEEEEETTTTEEEEEEEEEEBCCHHHHHHHHHHHTCTTGGGSHHHHHHHTTCSCCEEEEEEEHHHHHHHHHTCSCGGGTSCCCCCHHHHHHCCSCC

In [22]:
print( reco_0_v2[0,0:68] )

[  0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   1.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   1.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   1.           0.           0.           0.           0.
   0.           0.           0.39338122   1.           1.
   1.           0.           1.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           1.
   0.           0.         200.1       ]
